version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - odoo-net
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/html
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/data:/var/www/html
  #     - ./certbot/logs:/var/log/letsencrypt
  #   depends_on:
  #     - web
  #   command: certonly --webroot --webroot-path=/var/www/html 
  #           --email paolo.dev.projects@gmail.com 
  #           --agree-tos --no-eff-email -d yourdomain.com -d www.yourdomain.com
  odoo:
    build: .
    container_name: odoo
    depends_on:
      - web
      - db
    user: root
    networks:
      - odoo-net
    volumes:
      - odoo-data:/var/lib/odoo:rw
      - ./enterprise:/mnt/enterprise:rw
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/extra-addons:rw
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=superscret  # set the superuser password
    command:
    #- --dev=all
    - --workers=2
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - odoo-net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=superscret # set a superuser password here
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data:rw
volumes:
  odoo-data:
  odoo-db:

networks:
  odoo-net:
    driver: bridge